//fetch AI
export const FETCH_AI_REQUEST = 'FETCH_AI_REQUEST';
export const FETCH_AI_SUCCESS = 'FETCH_AI_SUCCESS';
export const FETCH_AI_FAILURE = 'FETCH_AI_FAILURE';

//post AI
export const FETCH_POST_AI_REQUEST = 'FETCH_POST_AI_REQUEST';
export const FETCH_POST_AI_SUCCESS = 'FETCH_POST_AI_SUCCESS';
export const FETCH_POST_AI_FAILURE = 'FETCH_POST_AI_FAILURE';