//fetch ChatBot
export const FETCH_BOT_REQUEST = 'FETCH_BOT_REQUEST';
export const FETCH_BOT_SUCCESS = 'FETCH_BOT_SUCCESS';
export const FETCH_BOT_FAILURE = 'FETCH_BOT_FAILURE';

//post ChatBot
export const POST_BOT_REQUEST = 'POST_BOT_REQUEST';
export const POST_BOT_SUCCESS = 'POST_BOT_SUCCESS';
export const POST_BOT_FAILURE = 'POST_BOT_FAILURE';

//updat ChatBot
export const UPDATE_BOT_REQUEST = 'UPDATE_BOT_REQUEST';
export const UPDATE_BOT_SUCCESS = 'UPDATE_BOT_SUCCESS';
export const UPDATE_BOT_FAILURE = 'UPDATE_BOT_FAILURE';

//delete ChatBot
export const DELETE_BOT_REQUEST = 'DELETE_BOT_REQUEST';
export const DELETE_BOT_SUCCESS = 'DELETE_BOT_SUCCESS';
export const DELETE_BOT_FAILURE = 'DELETE_BOT_FAILURE';

//fetch reyal time data
export const FETCH_REYAL_TIME_BOT = 'FETCH_REYAL_TIME_BOT';

//check websoket
export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';

